config/routes.rb
Rails.application.routes.draw do
 
  root 'links#index'

  resources :links, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  get '/newcomments' => 'comments#index'
  get '/newest' => 'links#newest', as: :newest_links
  get "/:page" => "static_pages#about"
  get '/links/next', 'links#next'

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create]
  
  namespace 'v0', format: :json do
    resources :links, only: [:show, :create]
    resources :comments, only: [:show]
  end
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul class="errors alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
      <a href="https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2">API</a>
      |
      <%= link_to "About", "/about" %>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <%= image_tag("rmitlogo.JPG", :alt => "rmit logo", style: 'height:20%;width:20%') %>

    <div class="navlinks">
      <%= link_to "Home", root_path, class: "logo" %>
      <%= link_to "comments", newcomments_path %>

      <% unless logged_in? %>
        <%= link_to "login", new_user_path %>
        
      <% end %>

      <% if logged_in? %>
        <%= link_to "Submit a news", new_link_path %>
        <%= link_to "logout", sessions_path, method: :delete %>
      <% end %>
    </div>
  </nav>
</header>