config/routes.rb
Rails.application.routes.draw do
 
  root 'links#index'

  resources :links, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  get '/newcomments' => 'comments#index'
  get '/newest' => 'links#newest', as: :newest_links
  get "/:page" => "static_pages#about"
  get '/links/next', 'links#next'

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create]
  
  namespace 'v0', format: :json do
    resources :links, only: [:show, :create]
    resources :comments, only: [:show]
  end
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :votes

  scope :hottest, -> { order(hot_score: :desc) }
  scope :newest, -> { order(created_at: :desc) }

  validates :title,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 10, maximum: 200 },
            format: { with: /\s[\w-]+\z/, message: "Must be at least 10 characters (including white spaces, new lines and tabs) "}
  validates :url,
            format: { with: %r{\Ahttps?://} },
            allow_blank: true

  def comment_count
    comments.length
  end
  
  def next
    Link.newest.limit(8).offset((@page - 1) * 8)
  end

  def set_page
    @page = params[:page] || 0
  end

  def upvotes
    votes.sum(:upvote)
  end

  def downvotes
    votes.sum(:downvote)
  end

  private

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :prevent_unauthorized_user_access, except: [:show, :index]

  def index
    @page = params['page'].to_i
    @next_page = @page + 1
    @links = Link.newest.limit(8).offset(@page * 8)
  end

  def newest
    @links = Link.newest
  end
  
  def set_page
    @page = params[:page] || 0
  end


  def new
    @link = Link.new
  end

  def show
    @link = Link.find_by(id: params[:id])
    @comments = @link.comments
  end

  def edit
    perform_action(:edit) { |link| @link = link }
  end

  def update
    @link = current_user.links.find_by(id: params[:id])

    if @link.update(link_params)
      redirect_to root_path, notice: 'Link successfully updated'
    else
      render :edit
    end
  end

  def create
    @link = current_user.links.new(link_params)

    if @link.save
      redirect_to root_path, notice: 'Link successfully created'
    else
      render :new
    end
  end

  def destroy
    perform_action(:delete) do |link|
      link.destroy
      redirect_to root_path, notice: 'Link successfully deleted'
    end
  end

  def upvote
    link = Link.find_by(id: params[:id])

    if current_user.upvoted?(link)
      current_user.remove_vote(link)
    elsif current_user.downvoted?(link)
      current_user.remove_vote(link)
      current_user.upvote(link)
    else
      current_user.upvote(link)
    end

    link.calc_hot_score
    redirect_to root_path
  end

  def downvote
    link = Link.find_by(id: params[:id])

    if current_user.downvoted?(link)
      current_user.remove_vote(link)
    elsif current_user.upvoted?(link)
      current_user.remove_vote(link)
      current_user.downvote(link)
    else
      current_user.downvote(link)
    end

    link.calc_hot_score
    redirect_to root_path
  end

  private

  def perform_action(action)
    link = Link.find_by(id: params[:id])

    if current_user.owns_link?(link)
      yield(link) if block_given?
    else
      redirect_to root_path, notice: "Not authorized to #{action} this link"
    end
  end

  def link_params
    params.require(:link).permit(:title, :url, :description)
  end
end

app/controllers/v0/links_controller.rb
class V0::LinksController < ApplicationController
  def show
    @link = Link.find(params[:id])
  end
  
  def create
    @link = Link.new(create_params)
    @link.user = current_user
    
    if @link.save
      render :show
    else
      render json: @link.errors.full_messages.join('.'), status: 400
    end
  end
  
  private
  
  def create_params
    params.require(:link).permit(:title, :url)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/v0/links_helper.rb
module V0::LinksHelper
end

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <%= render "shared/errors", object: @link %>

  <div class="form-group">
    <%= f.text_field :title, required: true, class: "form-control", placeholder: "title" %>
  </div>

  <div class="form-group">
    <%= f.url_field :url, class: "form-control", placeholder: "url" %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, class: "form-control", placeholder: "description", rows: 15 %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div class="link">
  <div class="title">
    <%= link_to link.title, (link.url? ? link.url : link) %>

    <% if link.url? %>
      <span>
        ( <%= link.url %> )
      </span>
    <% end %>
  </div>

  <div class="metadata">
    <span class="points">
      <%= pluralize(link.points, 'point') %> by <%= link.user.username %>
    </span>

    <span class="time-created">
      <%= time_ago_in_words(link.created_at) %> ago
    </span>

    <span class="comment-count">
      <%= link_to pluralize(link.comment_count, 'comment'), link %>
    </span>

    <% if logged_in? && current_user.owns_link?(link) %>
      <span class="edit-link">
        <%= link_to "edit", edit_link_path(link) %>
      </span>

      <span class="delete-link">
        <%= link_to "delete", link, method: :delete, data: { confirm: "Are you sure?" } %>
      </span>
    <% end %>
  
    <% if logged_in? %>
      <span class="upvote-link">
        <%= link_to "upvote (#{link.upvotes})", upvote_link_path(link), method: :post %>
      </span>

      <span class="downvote-link">
        <%= link_to "downvote (#{link.downvotes})", downvote_link_path(link), method: :post %>
      </span>
    <% end %>
  </div>
</div>

app/views/links/edit.html.erb
<section class="edit-link">
  <header>
    <h1>
      Edit link
    </h1>
  </header>

  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/links/index.html.erb
<%= content_for(:title, "Home Page ") %>
<section class="all-links">
  <%= render @links %>
</section>

<button><%= link_to "more", root_path(:page => @next_page) %></button>

app/views/links/new.html.erb
<%= content_for(:title, "submit ") %>

<section class="new-link">
  <header>
    <h1>
      submit a link
    </h1>
  </header>

  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/links/newest.html.erb
<section class="newest-links">
  <%= render @links %>
</section>

app/views/links/show.html.erb
<section class="link-thread">
  <header>
    <%= render @link %>

    <% if @link.description? %>
      <p>
        <%= @link.description %>
      </p>
    <% end %>
  </header>
  
  <% if logged_in? %>
    <div class="add-comment row">
      <div class="col-sm-6">
        <%= form_for :comment, url: link_comments_path(@link) do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Comment...", rows: 10, required: true %>
          </div>

          <div class="form-group">
            <%= f.button "add comment", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  
  <div class="all-comments row">
    <div class="col-sm-12">
      <% if @comments.present? %>
        <h3>
            Comments
        </h3>
      <% end %>
      
      <% @comments.each do |comment| %>
        <div class="comment">
          <p class="comment-owner">
            <strong>
              <%= comment.user.username %>
            </strong>

            <span class="comment-created small">
              <%= time_ago_in_words(comment.created_at) %> ago
            </span>
            
            <% if logged_in? && current_user.owns_comment?(comment) %>
              <span class="edit-comment">
                <%= link_to 'edit',  edit_link_comment_path(@link, comment) %>
              </span>

            <span class="delete-comment">
                 <%= link_to 'delete', link_comment_path(@link, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          <% end %>
          </p>

          <p>
            <%= comment.body %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</section>